create table if not exists carriages_schedule (
    ID INT auto_increment,
    NUMBER VARCHAR(20) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    DEPARTURE_STATION VARCHAR(255) NOT NULL,
    ARRIVAL_STATION VARCHAR(255) NOT NULL,
    DEPARTURE_TIME DATETIME NOT NULL,
    ARRIVAL_TIME DATETIME NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    primary key (ID)
);
